language: go
go:
 - 1.8
 - tip

before_install:
  - go get github.com/pkg/errors
  - go get github.com/google/go-cmp/cmp

script:
 - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)